// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Check is the predicate function for check builders.
type Check func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Website is the predicate function for website builders.
type Website func(*sql.Selector)
