// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gelleson/changescout/changescout/internal/domain"
	"github.com/gelleson/changescout/changescout/internal/infrastructure/database/ent/ent/user"
	"github.com/gelleson/changescout/changescout/internal/infrastructure/database/ent/ent/website"
	"github.com/gelleson/changescout/changescout/pkg/crons"
	"github.com/google/uuid"
)

// WebsiteCreate is the builder for creating a Website entity.
type WebsiteCreate struct {
	config
	mutation *WebsiteMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (wc *WebsiteCreate) SetName(s string) *WebsiteCreate {
	wc.mutation.SetName(s)
	return wc
}

// SetURL sets the "url" field.
func (wc *WebsiteCreate) SetURL(s string) *WebsiteCreate {
	wc.mutation.SetURL(s)
	return wc
}

// SetCron sets the "cron" field.
func (wc *WebsiteCreate) SetCron(ce crons.CronExpression) *WebsiteCreate {
	wc.mutation.SetCron(ce)
	return wc
}

// SetEnabled sets the "enabled" field.
func (wc *WebsiteCreate) SetEnabled(b bool) *WebsiteCreate {
	wc.mutation.SetEnabled(b)
	return wc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableEnabled(b *bool) *WebsiteCreate {
	if b != nil {
		wc.SetEnabled(*b)
	}
	return wc
}

// SetMode sets the "mode" field.
func (wc *WebsiteCreate) SetMode(s string) *WebsiteCreate {
	wc.mutation.SetMode(s)
	return wc
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableMode(s *string) *WebsiteCreate {
	if s != nil {
		wc.SetMode(*s)
	}
	return wc
}

// SetSetting sets the "setting" field.
func (wc *WebsiteCreate) SetSetting(d *domain.Setting) *WebsiteCreate {
	wc.mutation.SetSetting(d)
	return wc
}

// SetUserID sets the "user_id" field.
func (wc *WebsiteCreate) SetUserID(u uuid.UUID) *WebsiteCreate {
	wc.mutation.SetUserID(u)
	return wc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableUserID(u *uuid.UUID) *WebsiteCreate {
	if u != nil {
		wc.SetUserID(*u)
	}
	return wc
}

// SetNextCheckAt sets the "next_check_at" field.
func (wc *WebsiteCreate) SetNextCheckAt(t time.Time) *WebsiteCreate {
	wc.mutation.SetNextCheckAt(t)
	return wc
}

// SetLastCheckAt sets the "last_check_at" field.
func (wc *WebsiteCreate) SetLastCheckAt(t time.Time) *WebsiteCreate {
	wc.mutation.SetLastCheckAt(t)
	return wc
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableLastCheckAt(t *time.Time) *WebsiteCreate {
	if t != nil {
		wc.SetLastCheckAt(*t)
	}
	return wc
}

// SetCreatedAt sets the "created_at" field.
func (wc *WebsiteCreate) SetCreatedAt(t time.Time) *WebsiteCreate {
	wc.mutation.SetCreatedAt(t)
	return wc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableCreatedAt(t *time.Time) *WebsiteCreate {
	if t != nil {
		wc.SetCreatedAt(*t)
	}
	return wc
}

// SetUpdatedAt sets the "updated_at" field.
func (wc *WebsiteCreate) SetUpdatedAt(t time.Time) *WebsiteCreate {
	wc.mutation.SetUpdatedAt(t)
	return wc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableUpdatedAt(t *time.Time) *WebsiteCreate {
	if t != nil {
		wc.SetUpdatedAt(*t)
	}
	return wc
}

// SetID sets the "id" field.
func (wc *WebsiteCreate) SetID(u uuid.UUID) *WebsiteCreate {
	wc.mutation.SetID(u)
	return wc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (wc *WebsiteCreate) SetNillableID(u *uuid.UUID) *WebsiteCreate {
	if u != nil {
		wc.SetID(*u)
	}
	return wc
}

// SetUser sets the "user" edge to the User entity.
func (wc *WebsiteCreate) SetUser(u *User) *WebsiteCreate {
	return wc.SetUserID(u.ID)
}

// Mutation returns the WebsiteMutation object of the builder.
func (wc *WebsiteCreate) Mutation() *WebsiteMutation {
	return wc.mutation
}

// Save creates the Website in the database.
func (wc *WebsiteCreate) Save(ctx context.Context) (*Website, error) {
	wc.defaults()
	return withHooks(ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WebsiteCreate) SaveX(ctx context.Context) *Website {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WebsiteCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WebsiteCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WebsiteCreate) defaults() {
	if _, ok := wc.mutation.Enabled(); !ok {
		v := website.DefaultEnabled
		wc.mutation.SetEnabled(v)
	}
	if _, ok := wc.mutation.Mode(); !ok {
		v := website.DefaultMode
		wc.mutation.SetMode(v)
	}
	if _, ok := wc.mutation.CreatedAt(); !ok {
		v := website.DefaultCreatedAt()
		wc.mutation.SetCreatedAt(v)
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		v := website.DefaultUpdatedAt()
		wc.mutation.SetUpdatedAt(v)
	}
	if _, ok := wc.mutation.ID(); !ok {
		v := website.DefaultID()
		wc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WebsiteCreate) check() error {
	if _, ok := wc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Website.name"`)}
	}
	if v, ok := wc.mutation.Name(); ok {
		if err := website.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Website.name": %w`, err)}
		}
	}
	if _, ok := wc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Website.url"`)}
	}
	if v, ok := wc.mutation.URL(); ok {
		if err := website.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Website.url": %w`, err)}
		}
	}
	if _, ok := wc.mutation.Cron(); !ok {
		return &ValidationError{Name: "cron", err: errors.New(`ent: missing required field "Website.cron"`)}
	}
	if v, ok := wc.mutation.Cron(); ok {
		if err := website.CronValidator(string(v)); err != nil {
			return &ValidationError{Name: "cron", err: fmt.Errorf(`ent: validator failed for field "Website.cron": %w`, err)}
		}
	}
	if _, ok := wc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Website.enabled"`)}
	}
	if _, ok := wc.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Website.mode"`)}
	}
	if _, ok := wc.mutation.Setting(); !ok {
		return &ValidationError{Name: "setting", err: errors.New(`ent: missing required field "Website.setting"`)}
	}
	if _, ok := wc.mutation.NextCheckAt(); !ok {
		return &ValidationError{Name: "next_check_at", err: errors.New(`ent: missing required field "Website.next_check_at"`)}
	}
	if _, ok := wc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Website.created_at"`)}
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Website.updated_at"`)}
	}
	return nil
}

func (wc *WebsiteCreate) sqlSave(ctx context.Context) (*Website, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WebsiteCreate) createSpec() (*Website, *sqlgraph.CreateSpec) {
	var (
		_node = &Website{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(website.Table, sqlgraph.NewFieldSpec(website.FieldID, field.TypeUUID))
	)
	if id, ok := wc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wc.mutation.Name(); ok {
		_spec.SetField(website.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wc.mutation.URL(); ok {
		_spec.SetField(website.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := wc.mutation.Cron(); ok {
		_spec.SetField(website.FieldCron, field.TypeString, value)
		_node.Cron = value
	}
	if value, ok := wc.mutation.Enabled(); ok {
		_spec.SetField(website.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := wc.mutation.Mode(); ok {
		_spec.SetField(website.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := wc.mutation.Setting(); ok {
		_spec.SetField(website.FieldSetting, field.TypeJSON, value)
		_node.Setting = value
	}
	if value, ok := wc.mutation.NextCheckAt(); ok {
		_spec.SetField(website.FieldNextCheckAt, field.TypeTime, value)
		_node.NextCheckAt = value
	}
	if value, ok := wc.mutation.LastCheckAt(); ok {
		_spec.SetField(website.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = value
	}
	if value, ok := wc.mutation.CreatedAt(); ok {
		_spec.SetField(website.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wc.mutation.UpdatedAt(); ok {
		_spec.SetField(website.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := wc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   website.UserTable,
			Columns: []string{website.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WebsiteCreateBulk is the builder for creating many Website entities in bulk.
type WebsiteCreateBulk struct {
	config
	err      error
	builders []*WebsiteCreate
}

// Save creates the Website entities in the database.
func (wcb *WebsiteCreateBulk) Save(ctx context.Context) ([]*Website, error) {
	if wcb.err != nil {
		return nil, wcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Website, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebsiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WebsiteCreateBulk) SaveX(ctx context.Context) []*Website {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WebsiteCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WebsiteCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}
