version: "3"

services:
  changescout:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3311:3311"
    env_file:
      - .env
    volumes:
      - changescout-data:/opt/changescout/data

  changescout-chrome:
    image: ghcr.io/go-rod/rod:v0.116.2

volumes:
  changescout-data:
